In [ ]:
import mdtraj as md
import numpy as np
import matplotlib.pyplot as plt
import csv
import xlrd
import os
import os.path
from pathlib2 import Path
from decimal import *
%matplotlib inline
import matplotlib.pylab as pylab
params = {'legend.fontsize': 'x-large',
          'figure.figsize': (15, 5),
         'axes.labelsize': 'x-large',
         'axes.titlesize':'x-large',
         'xtick.labelsize':'x-large',
         'ytick.labelsize':'x-large',
         'font.weight':'medium', 
         'xtick.major.size':8,
         'ytick.major.size':8}
pylab.rcParams.update(params)

In [ ]:
filedir = '/gpfs/amarolab/monolayers/'

In [3]:
#laup_test_20 = md.load(filedir+'LAUP_NaCl0.4_GMX/SA20-1_100ns/step9_1.trr', top=filedir+'LAUP_NaCl0.4_GMX/SA20-1_100ns/step9_1.gro')
#laup_test_19 = md.load('/gpfs/amarolab/abbyflabby/LAU/LAUP_NaCl0.4/SA19/charmm-gui/namd/step7.1_production.dcd', top='/gpfs/amarolab/abbyflabby/LAU/LAUP_NaCl0.4/SA19/charmm-gui/step5_assembly.xplor_ext.psf')
#print(laup_test_20)
#print(laup_test_19)

<mdtraj.Trajectory with 10001 frames, 42576 atoms, 7674 residues, and unitcells>
<mdtraj.Trajectory with 5000 frames, 36223 atoms, 7721 residues, and unitcells>


In [4]:
#mix1_test_20 = md.load(filedir+'MIX1_NaCl0.4_GMX/SA20-3_100ns/concat.trr', top=filedir+'MIX1_NaCl0.4_GMX/SA20-3_100ns/step9_1.gro')
#mix1_test_19 = md.load(filedir+'MIX1_NaCl0.4_GMX/SA19-2_100ns/newtraj.trr', top=filedir+'MIX1_NaCl0.4_GMX/SA19-2_100ns/step9_1.gro')
#print(mix1_test_20)
print(mix1_test_19)

<mdtraj.Trajectory with 8001 frames, 46538 atoms, 7625 residues, and unitcells>
<mdtraj.Trajectory with 11901 frames, 47628 atoms, 7669 residues, and unitcells>


In [ ]:
#laup_test_20_s10 = md.load(filedir+'LAUP_NaCl0.4_GMX/SA20-1_100ns/step9_1.trr', top=filedir+'LAUP_NaCl0.4_GMX/SA20-1_100ns/step9_1.gro', stride=10)
#laup_test_19_s10 = md.load('/gpfs/amarolab/abbyflabby/LAU/LAUP_NaCl0.4/SA19/charmm-gui/namd/step7.1_production.dcd', top='/gpfs/amarolab/abbyflabby/LAU/LAUP_NaCl0.4/SA19/charmm-gui/step5_assembly.xplor_ext.psf', stride=10)
#mix1_test_20_s10 = md.load(filedir+'MIX1_NaCl0.4_GMX/SA20-3_100ns/concat.trr', top=filedir+'MIX1_NaCl0.4_GMX/SA20-3_100ns/step9_1.gro', stride=10)
mix1_test_19_s10 = md.load(filedir+'MIX1_NaCl0.4_GMX/SA19-2_100ns/newtraj.trr', top=filedir+'MIX1_NaCl0.4_GMX/SA19-2_100ns/step9_1.gro', stride=10)

In [ ]:
laup_test_20_s10_sel = laup_test_20_s10.top.select('resname LAUP')
laup_test_19_s10_sel = laup_test_19_s10.top.select('resname LAUP')
mix1_test_20_s10_sel = mix1_test_20_s10.top.select('resname LAUP or resname PALP or resname MYRP or resname STEP')
mix1_test_19_s10_sel = mix1_test_19_s10.top.select('resname LAUP or resname PALP or resname MYRP or resname STEP')

In [7]:
#compute contacts
laup20_res_select = laup_test_20.top.select('resname LAUP')
laup20 = laup_test_20.atom_slice(laup20_res_select)

In [8]:
laup19_res_select = laup_test_19.top.select('resname LAUP')
laup19 = laup_test_19.atom_slice(laup19_res_select)

In [9]:
mix120_res_select = mix1_test_20.top.select('resname LAUP or resname PALP or resname MYRP or resname STEP')
mix120 = mix1_test_20.atom_slice(mix120_res_select)
mix119_res_select = mix1_test_19.top.select('resname LAUP or resname PALP or resname MYRP or resname STEP')
mix119 = mix1_test_19.atom_slice(mix119_res_select)




In [20]:
L19 = md.compute_contacts(laup19[-1], scheme='closest', ignore_nonprotein=False)


[[0.20612238 0.19849272 0.2047376  ... 1.3624002  0.63857824 1.3601884 ]]


In [21]:
print(len(L19[0]))

1


In [17]:
#C = md.geometry.squareform(L19[0], L19[1])

In [19]:
#print(C[0])

[[0.        0.        0.        ... 6.7742786 6.410633  6.2427063]
 [0.        0.        0.        ... 7.2723813 6.884861  6.6323304]
 [0.        0.        0.        ... 6.4546833 6.181533  5.7807345]
 ...
 [6.7742786 7.2723813 6.4546833 ... 0.        0.        0.       ]
 [6.410633  6.884861  6.181533  ... 0.        0.        0.       ]
 [6.2427063 6.6323304 5.7807345 ... 0.        0.        0.       ]]
